#!/bin/sh

realfilepath="$(realpath $0)"
export include="${realfilepath}.d"

matchedconf="${include}/default.conf"
. ${matchedconf}

realfile="$(basename ${realfilepath})"
invocation="$(basename ${0})"

if [ ${realfile} = ${invocation} ]; then
  conf="${include}/${1}.conf"
  if [ -f ${conf} ]; then
    shift
    matchedconf=${conf}
    . ${matchedconf}
  fi
else
  for conf in ${include}/*.conf; do
    case "${invocation}.conf" in
    *${conf##*/})
      matchedconf=${conf}
      . ${matchedconf}
      break
      ;;
    esac
  done
fi

if [ "-d" = "${1}" ]; then
  echo "realfile   : ${realfile}"
  echo "invocation : ${invocation}"
  echo "include    : ${include}"
  echo "matchedconf: ${matchedconf}"
  echo "hosts      : ${hosts}"
  echo "commands   : ${commands}"
  exit
fi

if [ "-l" = "${1}" ]; then
  echo ${hosts}
  exit
fi

skipecho=0
if [ "-e" = "${1}" ]; then
  skipecho=1
  shift
fi

if [ -n "$*" ]; then
  commands="$*"
fi

for host in ${hosts}; do
  if [ ${skipecho} -lt 1 ]; then
    echo "-- ${host} --"
  fi
  ssh ${host} "${commands}"
  if [ ${skipecho} -lt 1 ]; then
    echo
  fi
done
